# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'telemed' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for telemed

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  target 'telemedTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'telemed-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for telemed-tvOS

  target 'telemed-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
